### ISSUE TITLE
Consider checksum'ing and signature-validating downloaded files (from setup-erlang)

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-elixir#11]
We're not doing that at the moment (`setup-erlang` and `setup-rebar3`).

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, is this desirable/possible? I thought the chars there in `builds.txt` were some kind of reference to a signature 🤣 but then I searched `bob` and it's just a commit SHA.

**Comment by ericmj** [comment]
We can add a checkum to builds.txt that can be used to verify the downloaded build but it won't give much additional security since builds.txt and the build are stored and fetched from the same place.

**Comment by paulo-ferraz-oliveira** [comment]
> it won't give much additional security since builds.txt and the build are stored and fetched from the same place.

Exactly, thus my question. I'll close this for now. @starbelly, feel free to reopen if you feel it important, since we've already somewhat discussed this.

Thanks, @ericmj.
