### ISSUE TITLE
Erlang/OTP / Elixir (comprehensive) compatibility list, for the action

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-elixir#18]
This list was compiled from using the action with the same content that gets it tested. It represents the combos that I found to be working / not working (in which case I add an "indication" of the Error). This is not the output of an automated task, and can easily be updated from now on, as versions keep coming out.

* `ubuntu-16.04`: the same as https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

* `ubuntu-18.04`

| Status | Elixir | Erlang/OTP | Error |
|-|-|-|-|
| 🚫 | 1.0 - 1.1 | 17 | ssl | 
| 🚫 | 1.0.5 - 1.5 | 18 | ssl | 
| 🚫 | 1.3 - 1.7 | 19 | ssl | 
| ✅ | 1.4.5 - 1.11 | 20, 21 | |
| ✅ | 1.6.6 - 1.11 | 21 | |
| ✅ | 1.10.3 - 1.11 | 23 | |

* `ubuntu-20.04`: the same as https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp, from 1.4.5 (Erlang/OTP versions prior to 20 not available in `ubuntu-20.04/builds.txt`)

Once all issues with SSL are solved the list might becomes

## Compatibility between Elixir and Ubuntu

| Elixir | Ubuntu |
|-|-|
| 1.0 - 1.11 | 16.04 |
| 1.0 - 1.11 | 18.04 |
| 1.4.5 - 1.11 | 18.04 |

**Comment by paulo-ferraz-oliveira** [comment]
I've created this Issue to discuss whether we want to change the presentation format in order to have this information in an `.md` referenced by `README.md` (or there, directly).

**Comment by starbelly** [comment]
I think that might be perfect for the README. 💯

**Comment by ericmj** [comment]
I don't think it's the actions job to document compatibility between Elixir and OTP versions, it's already documented here: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#content so we should reference that. Ideally we shouldn't have to document compatibility between OTP and OS versions either, but I don't think it's documented anywhere else.

I don't know why Elixir <1.4 is failing for you, it's working on hexpm/hex: https://github.com/hexpm/hex/blob/main/.github/workflows/main.yml#L39.

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, agreed: it's not the action's job to document compatibility (I was probably mislead by your "Sounds good 👍" reply to [the comment](https://github.com/erlef/setup-elixir/issues/7#issuecomment-804865448) where I imply it - but retract what I suggested). In any case, we now have an updatable reference, this issue, that consumers of the action can refer to if it's failing. (at least until it dies out in the closed Issues section)

---

As for `internal_error` failure here's a ref.: https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2189524443?check_suite_focus=true#step:3:14.

As for the `gen:debug_options` failure, here's a ref.: https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2189490836?check_suite_focus=true#step:3:14.

(I see the issues but know not enough about the Elixir/Erlang compat. to reason on them).

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, do you feel there's anything to look at regarding the failures I referenced in the previous message? Shall these make it to a new Issue, somewhere?

https://github.com/hexpm/hex/blob/main/.github/workflows/main.yml#L69 (the link you posted) shows the action using:
* Elixir v1.0.5 - d1c01facd3c2a511f495079e63e79da452de88ee6f9fbe68a5795fb06945fc7c
* Erlang OTP-17.3.4 - 9417f044ee3c291c2ea343c203aebdcc40597226

https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2189524443?check_suite_focus=true#step:3:14 (the link I posted) shows the action using:
* Elixir v1.0.5 - d1c01facd3c2a511f495079e63e79da452de88ee6f9fbe68a5795fb06945fc7c (**the same**)
* Erlang OTP-17.5.6.9 - 6d4001de141a00b3bf37b8f7b24c5bde2b4f4015 (not the same)

**Comment by ericmj** [comment]
Yes, they need to be fixed. Don't think a new issue should be created, it looks like a regression in the PR since it works on hexpm/hex.

The error here https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2189524443?check_suite_focus=true#step:3:14 seems to suggest an Elixir precompiled against the wrong OTP version is being used.

I checked our docker builds and they seem to be working for these versions:

```
> docker run -it hexpm/elixir:1.2.6-erlang-19.3.6.9-ubuntu-xenial-20200326 mix local.rebar --force
* creating root/.mix/rebar
* creating root/.mix/rebar3
> docker run -it hexpm/elixir:1.0.5-erlang-17.5.6.9-ubuntu-xenial-20200326 mix local.rebar --force
* creating root/.mix/rebar
```

**Comment by paulo-ferraz-oliveira** [comment]
> The error here https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2189524443?check_suite_focus=true#step:3:14 seems to suggest an Elixir precompiled against the wrong OTP version is being used.

For ref. I'm doing "v1.2.6-otp-19 on 19.3.6.9 (ubuntu-16.04)". I'll look at it closer.

In any case, some pointers:
- https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2189524443?check_suite_focus=true#step:3:8 shows we're pulling from https://repo.hex.pm/builds/otp/ubuntu-16.04/OTP-19.3.6.9.tar.gz [1] (supposedly the same you're using, which is why the test result becomes suspicious and may mean the PR effectively introduced a regression)
- https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2189524443?check_suite_focus=true#step:3:12 shows we're pulling from https://repo.hex.pm/builds/elixir/v1.2.6-otp-19.zip [1]

I'll create a branch for the current action to help us validate further.

---

[1] the pull request introduces no manipulation on input values to the shell scripts

**Comment by paulo-ferraz-oliveira** [comment]
The first difference I find is the action, as-is, doesn't allow for versions like `1.2.6-otp-19`, but that's probably a detail.

**Comment by ericmj** [comment]
I would suggest looking into if the correct Elixir and OTP versions/builds are being installed and used. The error you are getting happens when a regex is used on a different OTP version it was compiled on.

**Comment by paulo-ferraz-oliveira** [comment]
That's what I'm looking at, sure, but it crashes before I extract the versions 😄 I can confirm the present action (`main`) does not show the same symptoms: https://github.com/paulo-ferraz-oliveira/setup-elixir/runs/2193782731?check_suite_focus=true#step:7:4. I just haven't confirmed the emulator versions, yet.

**Comment by paulo-ferraz-oliveira** [comment]
I'll probably change the action to output the versions after install, so we can avoid not being able to understand this type of issue when it happens. I hope that's acceptable.

**Comment by starbelly** [comment]
> Ideally we shouldn't have to document compatibility between OTP and OS versions either, but I don't think it's documented anywhere else.

This was my reasoning behind supporting documenting it here, but perhaps it makes sense in elixir docs.

**Comment by starbelly** [comment]
> If anything is to be created here, we should create a new Issue, lest stuff gets hidden amongst our comments 😄

Not sure a new issue is warranted yet, depends on findings I believe. If a new issue is to be created anywhere, would be on elixir repo, but yes, still depends on findings first though IMO. Eric believes there are no problems, we are not sure.

**Comment by ericmj** [comment]
> Not sure a new issue is warranted yet, depends on findings I believe. If a new issue is to be created anywhere, would be on elixir repo, but yes, still depends on findings first though IMO. Eric believes there are no problems, we are not sure.

Elixir already documents compatibility between Elixir and OTP. Compatibility between OTP and Ubuntu would need to be documented somewhere though.

**Comment by starbelly** [comment]
> Elixir already documents compatibility between Elixir and OTP. Compatibility between OTP and Ubuntu would need to be documented somewhere though.

Right that's my point. For a moment I said, "elixir probably doesn't want to get this specific", but that's an assumption. @ericmj what do you think? Of course, still once again depends on further findings and validation of.

**Comment by ericmj** [comment]
Not sure if I follow what you mean. Elixir shouldn't document OTP and OS compatibility since it's not related to Elixir. It would need to be documented here or somewhere else.

**Comment by starbelly** [comment]
> Not sure if I follow what you mean. Elixir shouldn't document OTP and OS compatibility since it's not related to Elixir. It would need to be documented here or somewhere else.

Precisely 😁

**Comment by paulo-ferraz-oliveira** [comment]
I'm OK with documenting it here, since it pertains to action-specific stuff.
It can be done in a separate `.md` as to not overwhelm README (and because I'm assuming Erlang/OTP and Elixir won't be the two languages for which specific non-workaroundable action issues might arise).

**Comment by paulo-ferraz-oliveira** [comment]
I think for clarity (I might have been the one starting it) we should refrain from mentioning the pull request issues here. There's already a pull request for that. This Issue should pertain to the need to document stuff somewhere.

**Comment by paulo-ferraz-oliveira** [comment]
I'm closing this. I summarised my finding in "Compatibility between Elixir and Ubuntu" in the first message. If anyone feels this needs reopening feel free to do so.
