### ISSUE TITLE
Tag the newest v1 release with v1

### ISSUE THREAD

**Issue by chulkilee** [erlef/setup-elixir#3]
To allow github actions users to specify only the major version - this project needs to tag the latest `v1` version as `v1` - see https://github.com/actions/checkout/tree/v2 for example.

Right now `v1` is pointing to the commit of `v1.5.0`. Please update the tag 😄

**Comment by starbelly** [comment]
@chulkilee The tag has been updated. Let us know that all is working on your end ❤️

**Comment by chulkilee** [comment]
It works great! Thanks - closing it.
