### ISSUE TITLE
setup-elixir fails on ubuntu 20.04

### ISSUE THREAD

**Issue by jansenm** [erlef/setup-elixir#6]
`   /home/runner/work/_actions/erlef/setup-elixir/v1.0.0/src/install-otp-ubuntu 23.2.1
  Reading package lists...
  Building dependency tree...
  Reading state information...
  libwxbase3.0-0v5 is already the newest version (3.0.4+dfsg-15build1).
  libwxbase3.0-0v5 set to manually installed.
  0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
  Reading package lists...
  Building dependency tree...
  Reading state information...
  Package libwxgtk3.0-0v5 is not available, but is referred to by another package.
  This may mean that the package is missing, has been obsoleted, or
  is only available from another source
  
  E: Package 'libwxgtk3.0-0v5' has no installation candidate
  Error: The process '/home/runner/work/_actions/erlef/setup-elixir/v1.0.0/src/install-otp-ubuntu' failed with exit code 100`

the reason is apparently that the package was renamed from libwxgtk3.0-dev to libwxgtk3.0-gtk3-dev in ubuntu 20.04
.
ubuntu-latest was recently switched to 20.04 so i guess a lot of people will have this failure.

workaround: specify ubuntu-18.04 in runs-on

**Comment by ericmj** [comment]
Please include your workflow file.

**Comment by jansenm** [comment]
The project is free. The failing run https://github.com/jansenm/mj-inventory/runs/2030310646
The failing version: https://github.com/jansenm/mj-inventory/blob/48282ef808551ea89874093746f93c8ed3b34d46/.github/workflows/ci.yml

`
name: CI

on: push

jobs:
  test:
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}} / NodeJS ${{matrix.nodejs}}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [ '23.2.1' ]
        elixir: [ '1.11.2' ]
        nodejs: [ '12.x' ]

    steps:

      #
      ### CHECKOUT
      - name: Checkout Sources
        uses: actions/checkout@v2

      #
      ### SETUP VERSIONS
      - name: Setup Elixir
        # https://github.com/erlef/setup-elixir
        uses: erlef/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.nodejs}}

      #
      ### SETUP/CACHE DEPENDENCIES
      - name: Cache dependencies
        uses: actions/cache@v2
        id: deps-cache
        with:
          path: |
              deps/
              _build/dev/dialyxir*.plt
              _build/dev/dialyxir*.plt.hash
          key: ${{ runner.os }}-${{ matrix.otp}}-${{matrix.elixir}}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - run: mix local.rebar --force
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix local.hex --force
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.get
        if: steps.deps-cache.outputs.cache-hit != 'true'
      - run: mix deps.compile
        if: steps.deps-cache.outputs.cache-hit != 'true'

      #
      ### SETUP/CACHE NODE STUFF
      - name: Cache node_modules
        uses: actions/cache@v2
        id: node_modules-cache
        with:
          path: apps/inventory_web/assets/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/inventory_web/assets/package-lock.json')) }}
      - run: npm install --prefix assets
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        working-directory: apps/inventory_web

      #
      ### BUILD OUR NPM STUFF
      - run: npm run deploy --prefix assets
        working-directory: apps/inventory_web
      - run: mix phx.digest
        working-directory: apps/inventory_web

      #
      ### BUILD
      - run: mix compile
      - run: mix docs
      - name: Run mix credo
        run: |
          mix credo || (
          rc=$?

          # Only fail on warnings
          if (( $rc & 0x10 )) ; then
          echo "We have warnings"
          exit 1;
          fi
          )

      #
      ### TEST
      - run: mix compile
        env:
          MIX_ENV: test

      - run: mix test
        env:
          MIX_ENV: test

      - run: mix test --cover
        env:
          MIX_ENV: test

      #
      ### DIALYZER
      # we cached this as part of the dependencies above
      - if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          mix dialyzer --plt

      - run: mix dialyzer --no-check --halt-exit-status
`

**Comment by ericmj** [comment]
You should change this line:

```
uses: erlef/setup-elixir@v1.0.0
```

to this:

```
uses: erlef/setup-elixir@v1.0
```

to use the latest version.

**Comment by jansenm** [comment]
Just for anyone ever ending up here. The proposed solution does not work:

```
Current runner version: '2.277.1'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210302.0
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210302.0/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Failed to resolve action download info. Error: Unable to resolve action `erlef/setup-elixir@v1.0`, unable to find version `v1.0`
Retrying in 12.28 seconds
Failed to resolve action download info. Error: Unable to resolve action `erlef/setup-elixir@v1.0`, unable to find version `v1.0`
Retrying in 12.848 seconds
Error: Unable to resolve action `erlef/setup-elixir@v1.0`, unable to find version `v1.0`
```

This works

```
uses: erlef/setup-elixir@v1
```

And the latter actually comes from the documentation. I still had the 1.0.0 from some code i found before. Probably from when its was `action/` and not `erlef/`
