### ISSUE TITLE
Some minor "issues"

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-elixir#8]
While creating `erlef/setup-erlang` (heavily inspired by this one), I noticed two very small details that you might want to improve:
- [x] test.yml contains `npm test` (that's "failing", even though not signalling CI properly)
- [x] action.yml contains `author: GitHub` (which I changed to Erlang Ecosystem Foundation in my file)
- [x] ~~some licenses might be in need of review for `.licensed.yml` (or maybe not, since your CI runs fine: I wonder what the main differences are, though?)~~ apparently not applicable
- [x]  ~~setting `process.env.PATH` might have unintended side-effects (it did for me when I did that twice, but I'm probably missing something here; stuff seems to work without changing it too)~~ apparently not applicable

**Comment by paulo-ferraz-oliveira** [comment]
I'm also not sure how `.github` ends up inside `dist` (I don't think it's actually required there), but it does when we do `npm run build`.

**Comment by starbelly** [comment]
>  some licenses might be in need of review for .licensed.yml (or maybe not, since your CI runs fine: I wonder what the main differences are, though?)

Could you expand on that?

**Comment by paulo-ferraz-oliveira** [comment]
Try running `licensed` locally, on the project. If there's no issues presented, then there's no issue with the licenses. I assumed that, since I did that and some issues were presented (for `setup-erlang`) there might be some here too, which is why the actions state "might be... or maybe not".

**Comment by ericmj** [comment]
> setting process.env.PATH might have unintended side-effects (it did for me when I did that twice, but I'm probably missing something here; stuff seems to work without changing it too)

Can you elaborate on this? What are the unintended side-effects and what happened for you?

**Comment by paulo-ferraz-oliveira** [comment]
`wget` got reported as not being available, for example. Removing it seemed to do the trick. But also, I was doing it before running the `bash` script, so it's probably correlated.

In your case, for example, you already have `echo "$(pwd)/.setup-elixir/elixir/bin" >> $GITHUB_PATH` in the `bash` script. I'm not sure that shouldn't suffice.

**Comment by ericmj** [comment]
`wget` should in theory still be available since we only prepend to the path.

IIRC `process.env.PATH` is used to modify the PATH for the current action and `$GITHUB_PATH` is used to modify it for subsequent actions, we need to do both.

**Comment by paulo-ferraz-oliveira** [comment]
> `wget` should in theory still be available since we only prepend to the path.

Agree. Just not what I saw, unfortunately. And searching around the web I can't see examples for changing the `process.env` or what are the recommended practices. (I'll resolve this one, since in your case it seems to be a non-issue).
 
> IIRC `process.env.PATH` is used to modify the PATH for the current action and `$GITHUB_PATH` is used to modify it for subsequent actions, we need to do both.

My expectation exactly, but not what I observed. If you look at `setup-erlang`, it's working and you don't have those elements anymore (at the same time I'm not calling commands I just defined, like you do for `mix`, for example).

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, I think I found the culprit in my JS (while merging the actions). I was missing `:${process.env.PATH}`, much the same as if you miss that in `bash` you render your PATH "useless".

**Comment by paulo-ferraz-oliveira** [comment]
With the merge I'll hopefully have solved all issues except "action.yml contains author: GitHub (which I changed to Erlang Ecosystem Foundation in my file)". I took the liberty to adapt it to EEF. If y'all agree with this choice, this issue is good to be closed.

**Comment by paulo-ferraz-oliveira** [comment]
Closing due to "all actions resolved".
